### ISSUE TITLE
Potential Bug - Cannot use a global collection unless readDrafts access is set to true

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-demo#165]
Hey,

I'm noticing a potential bug with the access control on globals. Whenever I try to set readDrafts access to anything other than undefined it fails to load the admin panel and displays the following error in the console:

```
ERROR: There were 1 errors validating your Payload config
ERROR: 1: Globals "otter-access-token" > "access.readDrafts" is not allowed
```

This error applies to both having fine-tuned access and setting the access function to always return true

```js
readDrafts: () => true
```

I would preferably be able to set all the access control to false for globals as I want to use it to store sensitive data e.g. an access token for an external API. 

Recreate:

1. Create a global collection
2. Add access control
3. Define readDrafts access control
4. The admin panel will fail to load

**Comment by jmikrut** [comment]
Hey @mcornielje090404 — this is because `readDrafts` is not a real thing. 

If you want to prevent certain users from reading drafts, you need to follow the instructions in the docs:

https://payloadcms.com/docs/versions/drafts#restricting-draft-access

Basically, you return a query constraint that prevents certain users from reading documents unless `_status: 'published'`.

Does that make sense?
