### ISSUE TITLE
Drafts are showing in API results with drafts: false

### ISSUE THREAD

**Issue by abel-sch** [payloadcms/payload-3.0-demo#179]
As in described in title. 

Specifically querying for `_status: { equals: 'published'}` in local api filters out draft items. Drafts are also showing in REST API.
I'm using Postgres DB and on beta 23.

Not sure if this is related in any way but ever since I enabled versions every now and then I get this error:
`TypeError: Cannot destructure property 'collectionSlug' of 'reqData' as it is undefined.`

**Comment by jmikrut** [comment]
Hey there - so there are 2 things going on here:

1 - using “draft” set to true or false does not filter down to only docs that are published. Instead, it will send back newer drafts of published posts (if there are any). If you want only published docs, you need to query against the _status field as you saw. Often, access control is used to restrict unauthenticated users from seeing draft docs but that’s up you your use case. See what I mean?

2, if you want to enable versions on a collection that has not had them enabled but does have existing docs, you will need to create a migration that resaves each doc so that the corresponding versions are created. That is probably the reason why you’re seeing weird stuff happen.

does that make sense?

**Comment by abel-sch** [comment]
@jmikrut I might not have been completely clear;
I meant setting draft to true in my local api request (not the collection config):
```
const { docs } = await payload.find({
collection: 'pages',
depth: 1,
draft: false,
pagination: false,
where:
    { slug: { equals: slug } }, limit: 1
})
```

The Options type suggest a property called `draft` but this might be depricated?

The API tab in the CMS also shows a draft checkbox; which doesn't do anything.
<img width="396" alt="Screenshot 2024-05-04 at 16 23 19" src="https://github.com/payloadcms/payload-3.0-demo/assets/10962066/407c92e8-bfe4-47fd-8d33-aed91c3b73ce">

Adding a `where` query works fine, but the `draft` property does allow for a cleaner api.
