### ISSUE TITLE
Custom link option forces to select a document to link to

### ISSUE THREAD

**Issue by grvk** [payloadcms/payload-3.0-demo#189]
# Steps to Reproduce
1. Clone [payload-3.0-demo-bugs](https://github.com/grvk/payload-3.0-demo-bugs)
_Note: it's based of the latest demo code + upgraded to `beta.25`_
2. `npm install` (node version `v18.20.2`)
3. `./start-database.sh`
4. `npm run dev`
5. Log in
6. Click on "Pages"
7. In rich editor select "Add link" button
8. Select "Custom URL" option

# Expected Result
"Document" dropdown list is gone. We can only enter custom url & select whether we want the link to open in a new tab

# Actual Result
We're still forced to select a document to link to even though we're not choosing internal linking

# Recording

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/797cccb4-1a81-4a9f-9f30-62f27bd8b174

**Comment by PatrikKozak** [comment]
Hey @grvk - good catch and thank you for the reproducible repo! 

I was able to reproduce the issue with your repo.

Upon updating `payload` version from `3.0.0-beta.25` to `3.0.0-beta.28` (current) in your repo, the issue is resolved on my end. Give this a shot and let me know how it goes.

Going to close for now, if you experience different results, we can reopen.
