### ISSUE TITLE
Error when using the localAPI `.find` to get a collection.

### ISSUE THREAD

**Issue by ahmetskilinc** [payloadcms/payload-3.0-demo#209]
```javascript
const pages = await payload.find({
	collection: "pages"
});
```
```console
Error: The collection with slug pages can't be found. Find Operation.
   7 | const BeforeDashboard = async (props: Props) => {
>  8 | const pages = await payload.find({
     | 	                            ^
   9 | 		collection: "pages",
  10 | 	});
```
It does exist though, and I can get pages from the REST API.

[recreation repo](https://github.com/ahmetskilinc/recreation-repo-pages-collection-not-found)

**Comment by jmikrut** [comment]
So, you won't be able to just import `payload` anymore and use it straight-away.

You can now `import { getPayloadHMR } from '@payloadcms/next/utilities'` if you are working within Next.js, so that Payload will use hot module reloading, and you can use `import { getPayload } from 'payload'` if you are in a standalone script. 

Note that you also need to import your config and pass it to those functions as an arg.

Both of those scripts will automatically initialize Payload if it is not yet initialized, which will be the simpler way to go.

That will solve it for you!

**Comment by ahmetskilinc** [comment]
@jmikrut ah okay. So where do I import the config from? its not `import payload from 'payload'` or `import payloadConfig from '../payload.config'` is it?

**Comment by prizoner627** [comment]
@ahmetskilinc 

`import config from '@payload-config'
import { getPayloadHMR } from '@payloadcms/next/utilities'

async function getTour() {
  const payload = await getPayloadHMR({
    config,
  })
  const data = await payload.findByID({
    collection: 'tour',
    id: '66810f3e9b5e686ea17a5b25',
  })

  return data
}`
