### ISSUE TITLE
Root error pages and layout pages workaround

### ISSUE THREAD

**Issue by ahmetskilinc** [payloadcms/payload-3.0-demo#84]
When adding root error pages (`not-found.tsx` etc.) you're required to have a root `layout.tsx` file which would interfere with the `(payload)` route/directory.

A solution I've found to work is to do everything in the error file itself instead of having everything in the root layout. Also the generic Next 404 page shows up for the Payload Admin ui.

Something like:

`/layout.tsx` - empty, just renders `{children}`
`/not-found.tsx` - has all of the relevant parts from the `/(app)/layout.tsx` (below) file inside the error file.
`/(app)/layout.tsx` - has all app related stuff like normal.

Posting because it might help someone else but also because the payload team could've missed it.

**Comment by jmikrut** [comment]
Hey @ahmetskilinc can't you just put your error file within your `(app)` folder? Does that not work?

**Comment by ahmetskilinc** [comment]
@jmikrut Still shows the next 404 error page for some reason, tried it on Vercel and locally.

**Comment by jacobsfletch** [comment]
> Also the generic Next 404 page shows up for the Payload Admin ui.

@ahmetskilinc looks like we're missing the `[[...segements]]/not-found.tsx` page altogether. It must have simply not copied over properly. I've taken care of this with 9c881d6.

**Comment by ahmetskilinc** [comment]
@jacobsfletch Haha great

**Comment by iamlinkus** [comment]
So just to clarify since you’ve marked this as complete, @jacobsfletch , is the payload team recommending to use the workaround for the frontend not found, ir is there an actual solution that doesn’t need a “workaround”?

**Comment by jacobsfletch** [comment]
Thanks for the reply @iamlinkus 👍 Unfortunately we cannot add a root layout because we need the Payload Admin to have full control over its own `html` tag, etc. And similarly, we want you to have full control over your own app's root HTML. This is more of a Next.js issue, and it looks like others are experiencing the same issue: https://github.com/vercel/next.js/discussions/50034. There's a couple workarounds listed in that discussion, namely the catch-all page which fires `notFound()`. The underlying problem is specifically not found pages that result from unmatched routes, as opposed to those rendered as a result of bad API requests:

> Good to know: In addition to catching expected notFound() errors, the root app/not-found.js file also handles any unmatched URLs for your whole application. This means users that visit a URL that is not handled by your app will be shown the UI exported by the app/not-found.js file. Source: https://nextjs.org/docs/app/api-reference/file-conventions/not-found
